### ISSUE TITLE
Authentication does not work consistently

### ISSUE THREAD

**Issue by rohanajm7** [jashgopani/application-tracking-system#5] opened 2023-11-23 19:48 UTC
I have run the application multiple times and sometimes the authentication does not seem to work. 
Steps to reproduce the error are: 
- run ./startup.sh from the home directory
- try to login with appropriate credentials

**Comment by jashgopani** [comment] 2023-11-23 19:58
Hi @rohanajm7 please explain in more detail about the inconsistencies that you faced so that we can reproduce the issue accordingly.

**Comment by jashgopani** [comment] 2023-11-27 07:39
Hi @rohanajm7 
So far, in our testing, we haven't faced any issues with authentication. The issue you might be facing could be due to incorrect setup of database or google oauth credentials and redirect URL configuration.

I am closing this issue. Please try to setup the project properly and then if you face the issue again, you can re-open this issue.

**Closed by jashgopani** 2023-11-27 07:39 UTC
Labels: bug
